[package]
authors = ["cowboy8625 <cowboy8625@yahoo.com>"]
edition = "2018"
name = "rusty_rain"
version = "0.1.0"

[dependencies]
clap = "*"
crossterm = "0.18.2"
rand = "0.7.3"
buffy = { branch = "main", git = "https://github.com/cowboy8625/buffy.git" }

