[package]
name = "rusty-rain"
version = "0.0.1"
authors = ["cowboy8625 <cowboy8625@yahoo.com>"]
edition = "2018"

[dependencies]
clap = "*"
crossterm = "0.19.0"
rand = "0.8.2"
itertools = "0.10.0"

[profile.release]
debug = true
