[package]
name = "rusty-rain"
version = "0.1.0"
authors = ["cowboy8625 <https://github.com/cowboy8625>"]
edition = "2018"
description = "A cross platform CMatrix like program."
readme = "README.md"
repository = "https://github.com/cowboy8625/rusty-rain"
homepage = "https://github.com/cowboy8625/rusty-rain"
documentation = "https://docs.rs/rusty-rain"
license = "Apache-2.0"
license-file = "LICENSE"
keywords = ["matrix", "matrix rain", "cmatrix"]
categoriem = ["command-line-utilities"]

[dependencies]
clap = "*"
crossterm = "0.19.0"
rand = "0.8.2"
itertools = "0.10.0"

[profile.release]
debug = true
